# Generated by Django 6.1.1 on 2026-09-22 15:43

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва організатора')),
                ('contact_email', models.EmailField(max_length=254, verbose_name="Контакт для зв'язку")),
                ('verified', models.BooleanField(default=False, verbose_name='Підтверджений')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва події')),
                ('description', models.TextField(verbose_name='Опис')),
                ('category', models.CharField(choices=[('restaurants', 'Ресторани'), ('museums', 'Музеї'), ('nature', 'Природа'), ('party', 'Тусовки'), ('routes', 'Маршрути')], max_length=50, verbose_name='Категорія')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ціна (пусто=безкоштовно)')),
                ('start_time', models.DateTimeField(verbose_name='Початок події')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Кінець події')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Координати')),
                ('address', models.CharField(max_length=255, verbose_name='Адреса')),
                ('photo', models.ImageField(upload_to='events_photos/', verbose_name='Фото')),
                ('source_url', models.URLField(blank=True, null=True, verbose_name='Посилання на джерело')),
                ('status', models.CharField(choices=[('pending', 'Очікує модерації'), ('approved', 'Затверджено'), ('rejected', 'Відхилено')], default='pending', max_length=20, verbose_name='Статус')),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.organizer', verbose_name='Організатор')),
            ],
        ),
    ]
